# -*- coding: utf-8 -*-
"""Pookie_Bear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZQLO2pESmm2AWsoOadR0km_E_hXCq0r
"""

# important values for pop or delete functions that cannot be defined in main
entrances1 = ["- loud and ready to kick some butt", "- sneak in and catch them by suprise"]
entrances2 = [" - enter loud and ready to kill this dragon", "- sneak in and catch them by suprise"]
Cave_Task =["\n - are you the dragon?", "\n - I want to talk to you"]
end = ["\n - stay", "\n - leave"]
climb = ["\n - start climbing","\n - Look for another way in"]


#Actual game (defined as main to enable a fun little circle)
def main():
  print("\n You startle to the sound of an oddly familiar voice.")
  print("\n 'Hello there, you slept for quite a while, but I figured I'd best let you sleep until we arrived.' the stanger says.")
  print("\n 'You seem to have gotten rather banged up back there, I'm Spencer if you dont remember, but I dont think I ever did get your name?' ")

  Name = str(input())

  print( "\n 'Why hello there ", Name, ", and welcome to the kingdom of Veritas.'")
  print("\n 'Here you will find that adventure is always around the corner and danger is always closer than you might like.'")
  print("\n The wagons halts to a stop and Spencer runs out to help you out of the wagon and brushes any stray dirt and hay off your tunic.")
  print("\n 'Now lets get started by putting you to work aroung the town.'")

  Town_task = ("- slay the dragon", "- save the princess")
  print("\n First, we have a dragon who has killed everything that goes near it.")
  print("\n Next, we have the beautiful princess Vivienne, who has been locked in her tower since a young girl.")

  print("\n In short you can:")
  Town_task = ("- slay the dragon", "- save the princess")
  print(*Town_task,sep= '\n')
  task = input("\n So what would you like to do next? ")

  if task in Town_task:

    if task == "slay the dragon":
      Dragon_Story_Line()


  #Start of princess storyline
    else:
     Princess_Story_Line()
  else:
    print("\n Foolish adventurer, why don't we try that again.")
    return Pick_Task()
def Pick_Task():
  print("\n In short you can:")
  Town_task = ("- slay the dragon", "- save the princess")
  print(*Town_task,sep= '\n')

  task = input("\n So what would you like to do next? ")



  if task == "slay the dragon":
    Dragon_Story_Line()


  #Start of princess storyline
  else:
   Princess_Story_Line()

def Dragon_Story_Line():
  weapons = ["- the classic sword and shield", "\n - a cross bow and quiver", "\n - your words and wit"]
  print("\n so brave adventurer, you've chosen to slay the dragon, now chose your weapon of choice:")
  print(*weapons,sep= '\n')
  weapon = input("\n so what will you choose? ")
  if weapon in weapons:

    if weapon == "- the classic sword and shield":
      print("\n Armed with your brand new sword and shield you swiped from the royal armery you begin your trek to the dragons lair.")
      print("\n Upon the enterance your hear the beasts soft breaths echoing against the walls of the cave.")
      print("\n your are faced with one last choice before you enter the cave:")
      print(*entrances1,sep='\n')
      entrance1 = input("\n how will you enter? ")

      if entrance1 == "loud and ready to kick some butt":
        print("\n Though you try to look intimidating with your shiny new equipment, the dragon finds you to be a rather nusience.")
        print("\n The last words you hear before you feel an all consuming warmth take over your body is:")
        print("\n Foolish little", Name, "you thought you ever stood a chance.")
        print("\n And with a crash, you wake up back in the wagon where you arrived.")
        print("\n Ending 1: a foolish death")
        end1 = input()
        del entrance1[0]
        main()

      elif entrance1 == "sneak in and catch them by suprise":
        print("\n You do your best to sneak around the sided of the cave.")
        print("\n Unluckily for you, you sword and shield keep making a rather loud clanging sound which echos aroung the walls of the cavern.")
        print("\n You stop to try and fasten them down better, but you hear the beast breathing quiet.")
        print("\n You turn to check on the ruffian, and when you turn around you are met with a large amber orb meer inches from your face.")
        print("\n You here a deep chuckle as the mythical monster begins to speak....")
        print("\n 'Oh ", Name, " you are as stealthy as a drunkard in a tavern'")
        print("\n You feel an all consuming blaze devour your body and soul, before everything goes black and you wake up back in the wagon from which you arrived.")
        print("\n Ending 2: a drunkard in a tavern")
        end2 = input()
        entrance1.pop()
        main()

    else:
      print("\n You must have miss spoke, try that again adventurer.")
      return Dragon_Story_Line()



  elif weapon == "a cross bow and quiver":
    print("\n You start to make you way to the beast's cavern, practicing with your new cross bow on leaves and branches along the way.")
    print("\n As you near the caves threshold, you hear its raspy breaths echo from deep within,")
    print("\n and see the umistakeable flicker of fire grow and fade which each breath.")
    print("\n Before entering the cave you are faced with one last choice:")
    print(*entrances2,sep='\n')
    entrance2 = input("\n What kind of an entrance do you want to make? ")

    if entrance2 == "enter loud and ready to kill this dragon":
      print("\n You've decided to be loud. You want to strike fear into the heart of the dragon.")
      print("\n The dragon, however, is not nearly as scared as you hope, and seemingly unbothered.")
      print("\n Without even lifting her head, she burns you to a crisp, as if it didnt even disrupt her day to kill you.")
      print("\n Did your life even matter at all?")
      print("\n then you wake back in the wagon you arrived in.")
      print("\n Ending 3: Fading into oblivion")
      end3 = input()
      del entrances2[0]
      main()

    elif entrance2 == "- sneak in and catch them by suprise":
      print("\n You tie your gear close to your body to prepare to sneak in, not wanting it to clang loudly around as you enter")
      print("\n As you begin to travel deeper into the cave you notice drawing on the walls.")
      print("\n Images of the dragons past triumphs dance around you as you begin to feel a lump in your throught rise.")
      print("\n You've never done this before, you dont even have any idea how to kill a dragon, and even those who did didn't seem to stand a chance.")
      print("\n You can't do this, you have a family, i mean not that you can remeber at the moment but you know you have to have someone.")
      print("\n There in the cave, meer feet from the threshold, you decide to turn back.")
      print("\n You can't face the town after this failure, in fear and cowardess, you then spend the rest of your life in a town two kingdoms over.")
      print("\n You live a great life but the knowledge of your cowardess haunts you until the day of its end. Then, as if no time passed, you wake back in a familiar wagon.")
      print("\n Ending 4: A coward's burden")
      end4 = input()
      entrances2.pop()
      main()

    else:
      print("\n You must have miss spoke, try that again adventurer.")
      return enter2()

  else:
    print("\n Armed with only your brain, you bid farwell to Spencer and begin to make your way to the beast's lair.")
    print("\n As you walk through the forest towards the cave, you begin to see an alarming amount of warning signs near a cave entrance and make your way inside.")
    print("\n As you head toward the hearth of the cave system from which you hear its raspy breath, you keep stopping to view the drawing on the walls.")
    print("\n They depict horrid scenes of war, all of which lost by the human side as the dragons fire breath cosumes the army at hand.")
    print("\n Nearly all of them the same, yet so different, as you feel the need to run rise in your chest, you feel a hot breath across your cheek.")
    print("\n 'W h y   a r e   y o u   i n   m y   h o m e ?")
    print(*Cave_Task,sep= '\n')
    words = input("\n What will you say?")

    if words == "are you the dragon?":
      print("\n the last words you hear before the smell of burning flesh invades your senses are...")
      print("\n 'Dragon deez nuts on your face'")
      print("\n You then wake in the wagon from which you arrived severly confused and a little offended.")
      print("\n Ending 5: Gottem")
      end5 = input()
      del Cave_Task[0]
main()

    elif words == "I want to talk to you":
      print("\n 'It's so rare your kind wish to talk' the dragon says with an eye roll 'Of what do you wish to talk?'")
      print("\n You and the dragon, whose name you learned to be Rhea, talk for the rest of the night.")
      print("\n Once night falls, she invites you in, where you meet the three hatchlings she has been fighting to protect.")
      print("\n Their names of course are not in english so you decide to call them Joe, Jill, and baby Ray. The dragon is less than pleased but find it humerous.")
      print("\n You spend the rest of the night with the dragon family you have grown quite close with and the next day are invited to join them in the cave.")
      end = input("\n what will you do, stay or go?")

      if end == "stay":
        print(" \n You decide to stay in the cave with the family and live happily ever after as a little tribe, eventually adopting other beings who make their way into the cave.")
        print("\n One day, after you've grown old and the hatchlings have long left the cave, you wake back in the wagon from so long ago.")
        print("\n Ending 6: A happy family")
        end6 = input()
        main()


      else:
        print("\n Rhea understands, as you did just meet her the day before and bids you farwell, but promises to pick another village to pillage.")
        print("\n You return to your village where you are hailed as a hero for slaying the dragon, for they don't need to know the truth.")
        print("\n You fall in love with a towns girl and live a happy life with her and the three beautiful children she gave you, and a dog named rex.")
        print("\n Then one morning, after the childran have long left the house, and your hair has long grayed, you wake in a familiar wagon from all those years ago.")
        print("\n Ending 7: A cottagecore dream")
        end7 = input()
        main()
    else:
      print("\n what was that, speak up coward!")
      return words

def Pick_Weapon():
  weapons = ["- the classic sword and shield", "- a cross bow and quiver", "- your words and wit"]
  print(*weapons,sep= '\n')
  weapon = input("\n so what will you choose? ")

def enter1():
  print("\n your are faced with one last choice before you enter the cave:")
  print(*entrances1,sep='\n')
  entrance1 = input("\n how will you enter? ")

def enter2():
  print("\n Before entering the cave you are faced with one last choice:")
  print(*entrances2,sep='\n')
  entrance2 = input("\n What kind of an entrance do you want to make? ")

def Princess_Story_Line():
  print("\n 'Saving the princess? A valiant cause indeed' Spencer comments 'Plus its a good in to the royal family. Heres a map and some rations to aid you on your quest.'")
  print(" \n You begin to head along the path spencer marks out for you to the princesses tower, stoping at pubs and taverns along the way to eat and rest.")
  print("\n Though nothing of note happens until near the end of your adventure where you come across a rather sketchy bridge")
  print("\n The map Spencer had given you tells you to head around it, making it another three day trip, but if you cross it its only a couple hours walk to the tower")
  bridge = ("\n - Listen to the map", "\n - cross the bridge")
  print(*bridge, sep= '\n')
  Bridge = input ("\n What will you do?")

  if Bridge == "Listen to the map":
    print("\n Listening to the map, you decide to take the scenic route, it seems much safer anyway.")
    print("\n You continue your trot through the forest, collecting little trinkets and more flowers to give to the princess.")
    print("\n As you practice what you will say to her, thinking how crazy all the wild life must think you to be, you come across a downed birds nest.")
    print("\n You begin to approach it very causously and you see a bright red chested bird gaurding the vibrant blue eggs inside.")
    print("\n The poor mother bird is dragging its wing and looking less like a formidable gaurdian and more like a hurt child.")
    bird = input("\n Will you help them? yes or no ")

    if bird == "yes":
      print("\n Despite the mothers protests, you gently pick her up and fasten a sling for her out of some fabric you cut from your tunic.")
      print("\n Once she has been taken care of, you gently pick up the nest and fasten it ontop of you knapsack and place the mother gently on top with some of the rations Spencer gave you.")
      print("\n Realising you mean her no harm she calms down a little and begins to tend to the eggs, paying you little mind as you continue on your path.")
      print("\n After a few more days, and a couple of vilages, you finally reach the tower in which the princess resides.")
      print("\n With the couple of days rest the mother bird had regained the ability to fly and the eggs have just started pipping.")
      print("\n As you look upon the tall tower ahead of you, you sigh and grab some climbing materials from your bag, gently lay the nest on the ground, and start climbing.")
      print("\n After a taxing two hours of climbing, you hurl yourself onto the ledge of the princesses window. Scared you may be dead she rushes over to your aid.")
      print("\n 'Dear adventurer are you okay' She exclaims. You faintly say your name before losing consiousness.")
      pass_out = input()
      print("\n You awake after a time unknown to you, laying in the princesses bes, a damp towel on your head, and a small dog curled near your feet.")
      print("\n 'Quite a fright you gave me ", Name, "' she says 'I apologize for going through your stuff i needed to see if you had any medical supplise.")
      print("\n You look past her to see everything in your pack layed out nicely next to it. Just then you here the robin chirping desperatly at the windowsil for you.")
      print("\n To the princesses dismay, you jump up to calm the distraught bird and it nestles to your chest before cooing pleasantly.")
      print("\n Before long the princess joins you, causiously petting the birds head. Once the princess feels you are stong enough, you both leave the tower.")
      print("\n You make the long trek back to the castle to present her to the royal court. And within days, you've been married.")
      print("\n Your best man is of course the only person you can remember, Spencer, and you and Vivienne live a long and fufilling life in the castle.")
      print("\n Until one day, when your hair has long grayed and you've long retired from your royal duties, you wake back in the wagon from years ago.")
      print("\n Ending 8: A Helpful King")
      end8 = input()
      main()

    else:
      print("\n Deciding its a bird, so it probably doesnt need your help, you continue on your trail.")
      print("\n You pass through a couple more towns and villages before finally reaching the tower that the princess is kept.")
      print("\n You sigh, peering up at the massive climb infront of you, reach into your bag to grab some climbing materials, and start your climb.")
      print("\n After what feels like hours, you finally reach the ledge of the princesses window, and know gently on it.")
      print("\n The window flies open, nearly knocking you off, and you meet the stunning princess Vivienne.")
      print("\n 'Oh my god I'm so sorry' Vivienne says quickly 'Here come in'. You and vivienne spend the next couple of hours gettign know each other.")
      print("\n You and her watch the sun set from the tower and take of early the next morning. After nearly a week of traveling, you arrive at the castles gate.")
      print("\n The gates swing open, and the king and queen rush out the greet the princess. The king hugs you and thanks you for brining his daughter home to him, and offers her hand in marraige to you.")
      print("\n Within days, you are married to the Vivienne, and begin your decades long rule. You both grow old together, and long after your children have taken over the thrown you wake up.")
      print("\n like all those years ago, you are in a moving wagon, ready for another adventure.")
      print("\n Ending 9: A Royal Family")
      end9 = input()
      main()

  else:
    print("\n you start to cross the very sketcy bridge, letting out little gasps and shrieks as the planks creak and shift between your feet.")
    print("\n After what feels like days, you make it across the bridge, and with a few more hours of walking you make it to the princesses tower.")
    print("\n Looking at the climb before you, you have a choice to make:")
    print(*climb, sep= '\n')
    Climb = input("\n What will you do? ")

    if Climb == "start climbing":
      print("\n You grab some rope from your bag and begin climbing. After a couple of hours you reach the top.")
      print("\n You gently tap on the window, and the princess, who is even more stunning inperson, glides to the window to open it and invite you in.")
      print("\n You and Vivienne talk for hours, aboout nearly everything. Her voice is as smooth as silk and you feel yourself falling in love.")
      print("\n As the sun sets upon the tower, you and her dance to some of the records she has in the tower, before turning in for the night.")
      print("\n You take of early the next morning, heading back towards the castle. You arrive after a week of traveling, using the time to enchant Vivienne even more.")
      print("\n Once you arrive at the castle, you reintroduce her to the royal court, and she imediatly brings up mairrage to her father.")
      print("\n He agrees and you are married within the fortnight. You go on to raise a family with Vivienne, even strengthening the kingdom's economy through your rule.")
      print("\n Decades later when you have long passed the crown to your young, and the queen has passed peacefully, you wake in a familiar wagon, ready to start again.")
      print("\n Ending 10: A Loving Royal Ending")
      end10 = input()
      del climb[0]
      main()

    else:
      print("\n You circle the tower, looking for any other way into the tower. Under some ivy you see some suspisiously placed bricks.")
      print("\n You carefully remove them to find a door, after opening it you see a stair case. You light a torch and begin climbing the stairs.")
      print("\n painted across the walls of the staircase is artwork, ranging in beauty, as if the princess has been down here before.")
      print("\n You continue climbing, stopping every once in a while to admire the artwork, until you finally reach the top, where you see a trap door.")
      print("\n trying to be a spolite as you can while techniqually breaking and entering, you knock. The door swings open to reveal the absolutly stunning ptinceess.")
      print("\n with the light from the window behind her, she looks nearly angelic. 'What is your name brave adventurer?' she asks. Still fighting the cat who has a firm grasp on your tongue, you whisper you name.")
      print("\n She giggles 'well ", Name, " Its a pleasure to meet you'. You and Vivienne continue to talk and get to know one another throughout the night and once night falls, turn in.")
      print("\n The next morning you leave back to the castle, and in a weeks time of traveling arrive. You start to leave, but she invites you into the castle.")
      print("\n Once reunited with her parents she introduces you and brings up marriage. Though her parents are skeptical at first, they agree and you are wed withing the week.")
      print("\n You go on to rule for decades together, then long after the crown has been passed and your hair has greyed, she is squeezing your hand as you drift out of concoiusness.")
      print("\n when you wake, you are back in the wagon from a life time ago, to the voice of a friend.")
      print("\n Ending 11: The first to go.")
      end11 = input()
      del climb[1]
      main()


#the first part of code that actually runs lol
main()

